#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "markdown-it-py>=3",
#   "mdit-py-plugins>=0.4",
#   "ruamel.yaml>=0.18",
#   "unidiff>=0.7",
#   "tenacity>=8",
# ]
# ///
"""
spec-align.py -- keeps a project's specs and its implementation in step, for l3io-pm.

Subcommands: build, check-pointers, sections, disposition, check-dispositions, adrs,
check-links, lease, sync-plan, propose, commit, reject, check-stale, migrate-adrs.

It never calls a model. Each spec-alignment point in l3io-pm-execute runs one of these
first, and the result decides whether an agent is dispatched at all.

Global flags come before the subcommand: --project-root (required), --planning-root,
--impl-root, --state-root (default <impl-root>/state), --pm-status, --spec-paths JSON.

Exit codes: 0 ok; 1 a report-mode check found problems; 2 a gate refused, or bad input;
5 the spec-sync lease is held by another owner.

Design: docs/superpowers/specs/2026-09-11-spec-alignment-design.md in the package repo;
decisions: docs/adr/0004-agents-edit-architecture-specs.md, docs/adr/0005-one-adr-home.md.
"""
import argparse
import fnmatch
import glob
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile

INDEX_FORMAT = 1
INDEX_REL = os.path.join("spec", "spec-index.md")
INDEX_MAX_LEVEL = 3
SUMMARY_CHARS = 100
SIZE_WARN_BYTES = 16384
HEADER_TITLE = "# Spec index — generated by spec-align.py; do not edit"
DIGEST_RE = re.compile(r"^# inputs-sha256: ([0-9a-f]{64})\b")
SPEC_PATHS_RE = re.compile(r"^# spec-paths: (.*)$")

# Spec kinds in precedence order: a name matching several kinds takes the first. The
# architecture, ux and prd patterns are copied verbatim from
# l3io-util-doctor/steps/layout-cleanup.md heuristic 5 -- check-docs check 13 compares them.
KINDS = (
    ("architecture", ("*architecture*", "*arch-spec*", "*system-design*", "*tech-design*")),
    ("ux", ("*ux-spec*", "*ux-design*", "*wireframe*", "*mockup*", "*ui-spec*")),
    ("prd", ("*requirements*", "*prd*", "*brief*", "*spec*")),
    ("epics", ("*epics*",)),
)
KIND_ORDER = {k: i for i, (k, _) in enumerate(KINDS)}


class SAError(Exception):
    """A refusal: `code` is the exit status; the message goes to stderr."""

    def __init__(self, code, msg):
        super().__init__(msg)
        self.code = code


class Ctx:
    """The paths every subcommand resolves against, from the global flags."""

    def __init__(self, a):
        self.project = os.path.abspath(a.project_root)
        self.planning = os.path.abspath(a.planning_root) if a.planning_root else None
        self.impl = os.path.abspath(a.impl_root) if a.impl_root else None
        self.state_root = (os.path.abspath(a.state_root) if a.state_root
                           else (os.path.join(self.impl, "state") if self.impl else None))
        self.pm_status = a.pm_status or None
        self.spec_paths_arg = None
        if a.spec_paths is not None:
            try:
                value = json.loads(a.spec_paths)
            except ValueError as e:
                raise SAError(2, f"--spec-paths is not JSON: {e}")
            if not isinstance(value, list) or not all(isinstance(x, str) for x in value):
                raise SAError(2, "--spec-paths must be a JSON list of strings")
            self.spec_paths_arg = value

    def need(self, *what):
        flags = {"impl": ("--impl-root", self.impl), "state": ("--state-root", self.state_root),
                 "pm": ("--pm-status", self.pm_status)}
        missing = [flags[w][0] for w in what if not flags[w][1]]
        if missing:
            raise SAError(2, f"this subcommand needs {', '.join(missing)}")

    def rel(self, p):
        return os.path.relpath(os.path.abspath(p), self.project).replace(os.sep, "/")

    def abs(self, p):
        return p if os.path.isabs(p) else os.path.join(self.project, p)

    def index_path(self):
        self.need("impl")
        return os.path.join(self.impl, INDEX_REL)


def _under(path, root):
    path, root = os.path.abspath(path), os.path.abspath(root)
    return path == root or path.startswith(root + os.sep)


def read_text(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def atomic_write(path, text):
    """Write via a sibling temp file + os.replace, so a reader never sees half a file."""
    d = os.path.dirname(os.path.abspath(path))
    os.makedirs(d, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=d, prefix=".spec-align-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as fh:
            fh.write(text)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


# -- markdown ------------------------------------------------------------------------------ #

_MD = None


def md():
    """One parser for every read. Anchors are computed over every heading level, so duplicate
    suffixes (-1, -2) count the same headings GitHub does; the index lists H1-H3 only."""
    global _MD
    if _MD is None:
        from markdown_it import MarkdownIt
        from mdit_py_plugins.anchors import anchors_plugin
        _MD = MarkdownIt("commonmark").enable("table").use(anchors_plugin,
                                                           min_level=1, max_level=6)
    return _MD


class Section:
    __slots__ = ("level", "title", "anchor", "start", "end", "summary")

    def __init__(self, level, title, anchor, start, end, summary):
        self.level, self.title, self.anchor = level, title, anchor
        self.start, self.end, self.summary = start, end, summary


def first_sentence(text):
    s = " ".join(text.split())
    m = re.match(r"(.+?[.!?])(?:\s|$)", s)
    if m:
        s = m.group(1)
    return s if len(s) <= SUMMARY_CHARS else s[:SUMMARY_CHARS - 1].rstrip() + "…"


def parse_sections(text):
    """Every heading as a Section. A section runs from its heading line to the line before
    the next heading of the same or a higher level (1-based, inclusive)."""
    tokens = md().parse(text)
    nlines = len(text.splitlines())
    heads = [(i, int(t.tag[1:]), t.attrs.get("id"), t.map[0], tokens[i + 1].content.strip())
             for i, t in enumerate(tokens) if t.type == "heading_open"]
    out = []
    for n, (i, level, anchor, line0, title) in enumerate(heads):
        end = nlines
        for _, level2, _, line2, _ in heads[n + 1:]:
            if level2 <= level:
                end = line2
                break
        stop = heads[n + 1][0] if n + 1 < len(heads) else len(tokens)
        summary = ""
        for j in range(i + 3, stop):
            if (tokens[j].type == "paragraph_open" and j + 1 < stop
                    and tokens[j + 1].type == "inline"):
                summary = first_sentence(tokens[j + 1].content)
                break
        out.append(Section(level, title, anchor, line0 + 1, max(end, line0 + 1), summary))
    return out


# -- discovery and the catalog -------------------------------------------------------------- #

def kind_of(name):
    low = name.lower()
    for kind, patterns in KINDS:
        if any(fnmatch.fnmatchcase(low, p) for p in patterns):
            return kind
    return None


def _kind_for_path(p):
    """A file takes its own name's kind, else its directory's (a sharded doc's section)."""
    return kind_of(os.path.basename(p)) or kind_of(os.path.basename(os.path.dirname(p)))


def recorded_spec_paths(ctx):
    """The spec-paths list the current index was built with, or None."""
    if not ctx.impl:
        return None
    p = os.path.join(ctx.impl, INDEX_REL)
    if not os.path.isfile(p):
        return None
    with open(p, encoding="utf-8") as fh:
        for n, line in enumerate(fh):
            if n > 4:
                break
            m = SPEC_PATHS_RE.match(line.rstrip("\n"))
            if m:
                try:
                    value = json.loads(m.group(1))
                except ValueError:
                    return None
                return value if isinstance(value, list) else None
    return None


def effective_spec_paths(ctx):
    """--spec-paths when given; else the list the index records (so doctor, which cannot read
    pm-execute's customize.toml, checks the same spec set); else [] (discover)."""
    if ctx.spec_paths_arg is not None:
        return list(ctx.spec_paths_arg)
    rec = recorded_spec_paths(ctx)
    return rec if rec is not None else []


def discover(ctx):
    """[(project-relative path, kind)], sorted. spec_paths replaces discovery entirely."""
    found = {}
    skip = os.path.join(ctx.impl, "spec") if ctx.impl else None      # never index the index
    patterns = effective_spec_paths(ctx)
    if patterns:
        for pat in patterns:
            for hit in glob.glob(os.path.join(ctx.project, pat), recursive=True):
                if os.path.isfile(hit) and hit.endswith(".md") and not (skip and _under(hit, skip)):
                    found[ctx.rel(hit)] = _kind_for_path(hit) or "other"
    elif ctx.planning and os.path.isdir(ctx.planning):
        for dirpath, dirnames, filenames in os.walk(ctx.planning):
            if skip and _under(dirpath, skip):
                dirnames[:] = []
                continue
            keep = []
            for d in sorted(dirnames):
                full = os.path.join(dirpath, d)
                kind = kind_of(d)
                if skip and _under(full, skip):
                    continue
                if kind and os.path.isfile(os.path.join(full, "index.md")):
                    for sub_dir, _, sub_files in os.walk(full):
                        for f in sub_files:
                            if f.endswith(".md"):
                                found[ctx.rel(os.path.join(sub_dir, f))] = kind
                else:
                    keep.append(d)
            dirnames[:] = keep
            for f in filenames:
                if f.endswith(".md"):
                    kind = kind_of(f)
                    if kind:
                        found[ctx.rel(os.path.join(dirpath, f))] = kind
    return sorted(found.items())


def load_catalog(ctx):
    """{rel: {"kind", "sections", "anchors", "error", "sha"}} for every discovered spec."""
    cat = {}
    for rel, kind in discover(ctx):
        e = {"kind": kind, "sections": [], "anchors": {}, "error": None, "sha": ""}
        try:
            with open(ctx.abs(rel), "rb") as fh:
                raw = fh.read()
        except OSError as exc:
            e["error"], e["sha"] = f"unreadable: {exc.strerror or exc}", "unreadable"
        else:
            e["sha"] = hashlib.sha256(raw).hexdigest()
            try:
                text = raw.decode("utf-8")
            except UnicodeDecodeError:
                e["error"] = "not UTF-8"
            else:
                e["sections"] = parse_sections(text)
                e["anchors"] = {s.anchor: s for s in e["sections"]}
        cat[rel] = e
    return cat


def inputs_hash(ctx, cat):
    h = hashlib.sha256()
    h.update(f"format={INDEX_FORMAT}\n"
             f"spec-paths={json.dumps(effective_spec_paths(ctx))}\n".encode())
    for rel in sorted(cat):
        h.update(f"{rel}\0{cat[rel]['sha']}\n".encode())
    return h.hexdigest()


def render_index(ctx, cat, digest):
    body, skipped, n_specs, n_sections = [], [], 0, 0
    for rel in sorted(cat, key=lambda r: (KIND_ORDER.get(cat[r]["kind"], 99), r)):
        e = cat[rel]
        if e["error"]:
            skipped.append(f"- skipped: {rel} ({e['error']})")
            continue
        n_specs += 1
        body.append(f"## {e['kind']} · {rel}")
        for s in e["sections"]:
            if s.level > INDEX_MAX_LEVEL:
                continue
            n_sections += 1
            summary = f": {s.summary}" if s.summary else ""
            body.append(f"- {rel}#{s.anchor} — {s.title}{summary} (L{s.start}–{s.end})")
    if skipped:
        body += ["## skipped", *skipped]
    if not cat:
        body.append("no spec docs found")
    text = "\n".join(body) + "\n"
    nbytes = len(text.encode("utf-8"))            # R12: the body below the header
    header = (f"{HEADER_TITLE}\n"
              f"# inputs-sha256: {digest}  ·  bytes: {nbytes:,}  ·  specs: {n_specs}  ·  "
              f"sections: {n_sections}\n"
              f"# spec-paths: {json.dumps(effective_spec_paths(ctx))}\n")
    return header + text, nbytes, n_specs, n_sections


def index_digest(path):
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as fh:
        for n, line in enumerate(fh):
            if n > 4:
                break
            m = DIGEST_RE.match(line)
            if m:
                return m.group(1)
    return None


def cmd_build(ctx, a):
    path = ctx.index_path()
    cat = load_catalog(ctx)
    digest = inputs_hash(ctx, cat)
    fresh = index_digest(path) == digest
    if a.check:
        if fresh:
            print(f"OK build --check: {ctx.rel(path)} is fresh")
            return 0
        print(f"STALE {ctx.rel(path)}: the specs changed since it was built "
              f"(or it does not exist) -- run build")
        return 1
    if a.if_stale and fresh:
        print(f"OK build: {ctx.rel(path)} is fresh; not rewritten")
        return 0
    text, nbytes, n_specs, n_sections = render_index(ctx, cat, digest)
    atomic_write(path, text)
    if nbytes > SIZE_WARN_BYTES:
        sys.stderr.write(f"WARN spec index is {nbytes:,} bytes (> {SIZE_WARN_BYTES:,}); every "
                         f"reviewer reads it -- consider trimming (spec §8)\n")
    print(f"OK build: wrote {ctx.rel(path)} ({n_specs} spec(s), {n_sections} section(s), "
          f"{nbytes:,} bytes)")
    return 0


# -- provenance pointers ---------------------------------------------------------------------- #

# The six technical-AC dimensions, in the order the enrichment prompt writes them
# (steps/sprint/step-02-story-prep.md §2). check-docs check 13 compares this tuple with the
# prompt's layout block; keep it a literal, one name per line.
DIMENSIONS = (
    "Interface contracts",
    "Error and edge case handling",
    "Observability requirements",
    "Security considerations",
    "Testability approach",
    "Existing-library check",
)
TAC_HEADING = "Technical acceptance criteria"
SPEC_LINE_RE = re.compile(r"^\s*(?:[-*]\s+)?Spec:\s*(.*?)\s*$")
NONE_RE = re.compile(r"^none\s*(?:—|--|-)\s*(\S.*)$", re.I)
PTR_RE = re.compile(r"^([^\s#`]+\.md)#([^\s#`]+)$")
NA_RE = re.compile(r"^\s*N/A\s*(?:—|--|-)\s*\S")


def story_dimensions(text):
    """(found, {casefolded dimension: (h3 line, [(lineno, line), ...])}) under the story's
    `## Technical acceptance criteria`. Lines inside fenced or indented code are dropped."""
    tokens = md().parse(text)
    lines = text.splitlines()
    fenced = set()
    for t in tokens:
        if t.type in ("fence", "code_block") and t.map:
            fenced.update(range(t.map[0], t.map[1]))
    heads = [(t.map[0], int(t.tag[1:]), tokens[i + 1].content.strip())
             for i, t in enumerate(tokens) if t.type == "heading_open"]
    tac = next((ln for ln, lvl, title in heads
                if lvl == 2 and title.casefold() == TAC_HEADING.casefold()), None)
    if tac is None:
        return False, {}
    tac_end = next((ln for ln, lvl, _ in heads if ln > tac and lvl <= 2), len(lines))
    h3 = [(ln, title) for ln, lvl, title in heads if tac < ln < tac_end and lvl == 3]
    dims = {}
    for n, (ln, title) in enumerate(h3):
        end = h3[n + 1][0] if n + 1 < len(h3) else tac_end
        body = [(i + 1, lines[i]) for i in range(ln + 1, end) if i not in fenced]
        dims[title.casefold()] = (ln + 1, body)
    return True, dims


def resolve_pointer(cat, value):
    """((path, anchor, Section, kind), None) or (None, why)."""
    m = PTR_RE.match(value.strip().strip("`"))
    if not m:
        return None, f"not a pointer: {value!r} (expected <path>#<anchor>)"
    path, anchor = m.groups()
    e = cat.get(path)
    if e is None:
        return None, f"{path} is not in the spec index"
    if e["error"]:
        return None, f"{path} is unreadable ({e['error']})"
    s = e["anchors"].get(anchor)
    if s is None:
        return None, f"{path} has no anchor #{anchor}"
    return (path, anchor, s, e["kind"]), None


def story_pointers(text):
    """[(lineno, dimension, value)] for every Spec: line under a known dimension."""
    found, dims = story_dimensions(text)
    out = []
    for dim in DIMENSIONS:
        for n, line in (dims.get(dim.casefold()) or (0, []))[1]:
            m = SPEC_LINE_RE.match(line)
            if m:
                out.append((n, dim, m.group(1)))
    return out


def check_story(cat, text):
    """None when the story has no AC section (pre-provenance), else a list of problems."""
    found, dims = story_dimensions(text)
    if not found:
        return None
    errs = []
    for dim in DIMENSIONS:
        d = dims.get(dim.casefold())
        if d is None:
            errs.append((0, f"{dim}: missing dimension (### {dim})"))
            continue
        h3_line, body = d
        content = [(n, line) for n, line in body if line.strip()]
        if not content:
            errs.append((h3_line, f"{dim}: empty"))
            continue
        if NA_RE.match(content[0][1]):
            continue
        specs = [(n, SPEC_LINE_RE.match(line).group(1)) for n, line in content
                 if SPEC_LINE_RE.match(line)]
        if not specs:
            errs.append((h3_line, f"{dim}: no Spec: line -- end it with `Spec: <path>#<anchor>` "
                                  f"or `Spec: none — <reason>`"))
            continue
        nones = [(n, v) for n, v in specs if v.lower().startswith("none")]
        if nones:
            if len(specs) > 1:
                errs.append((nones[0][0], f"{dim}: `Spec: none` must be the only Spec: line"))
            elif not NONE_RE.match(nones[0][1]):
                errs.append((nones[0][0], f"{dim}: `Spec: none` needs a reason after the dash"))
            continue
        for n, v in specs:
            hit, why = resolve_pointer(cat, v)
            if hit is None:
                errs.append((n, f"{dim}: {why}"))
    return errs


def all_story_files(ctx):
    ctx.need("impl")
    return sorted(glob.glob(os.path.join(ctx.impl, "epic-*", "sprint-*", "stories", "*.md")))


def cmd_check_pointers(ctx, a):
    cat = load_catalog(ctx)
    stories = all_story_files(ctx) if a.all else [ctx.abs(s) for s in a.story]
    broken, pre = 0, []
    for s in stories:
        rel = ctx.rel(s)
        try:
            text = read_text(s)
        except (OSError, UnicodeDecodeError) as e:
            sys.stderr.write(f"{rel}: unreadable ({e})\n")
            broken += 1
            continue
        errs = check_story(cat, text)
        if errs is None:
            pre.append(rel)
            if not a.all:
                sys.stderr.write(f"{rel}: pre-provenance: no '## {TAC_HEADING}' section -- "
                                 f"treat it as thin and enrich it\n")
                broken += 1
            continue
        for n, msg in errs:
            sys.stderr.write(f"{rel}:{n}: {msg}\n")
        broken += bool(errs)
    if a.all:
        for rel in pre:
            print(f"INFO pre-provenance: {rel}")
        if broken:
            print(f"check-pointers --all: {broken} story file(s) with broken pointers")
            return 1
        print(f"OK check-pointers --all: {len(stories)} story file(s), "
              f"{len(pre)} pre-provenance")
        return 0
    if broken:
        return 2
    print(f"OK check-pointers: {len(stories)} story file(s)")
    return 0


def cmd_sections(ctx, a):
    cat = load_catalog(ctx)
    seen = {}
    for s in a.stories:
        for _, _, value in story_pointers(read_text(ctx.abs(s))):
            hit, _ = resolve_pointer(cat, value)
            if hit is not None:
                seen[(hit[0], hit[1])] = hit[2]
    for (path, anchor), sec in sorted(seen.items(), key=lambda kv: (kv[0][0], kv[1].start)):
        print(f"{path}#{anchor} L{sec.start}–{sec.end}")
    if not seen:
        print("(no resolvable pointers)")
    return 0


# -- drift dispositions ----------------------------------------------------------------------- #

DISPOSITIONS = ("resolved-in-code", "adr-justified", "spec-updated", "spec-proposal")
SPEC_DISPOSITIONS = ("spec-updated", "spec-proposal")
# R1: epic findings AD-{n}; sprint findings SD-{sprint nn}-{n}, unique across an epic.
FINDING_ID_RE = re.compile(r"^(AD-\d+|SD-\d{2}-\d+)$")
SEVERITIES = ("BLOCKER", "MAJOR", "MINOR")
EXPECT_RE = re.compile(r"Blocker:\s*(\d+),\s*Major:\s*(\d+),\s*Minor:\s*(\d+)", re.I)
DISP_FILE = "drift-dispositions.yaml"


def _yaml():
    from ruamel.yaml import YAML
    y = YAML()
    y.width = 4096
    y.preserve_quotes = True
    return y


def load_yaml(path):
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as fh:
        return _yaml().load(fh)


def dump_yaml(path, data):
    import io
    buf = io.StringIO()
    _yaml().dump(data, buf)
    atomic_write(path, buf.getvalue())


def md_tables(text):
    """Every markdown table as a list of rows (header row first), cells as plain text."""
    tables, rows, row = [], None, None
    for t in md().parse(text):
        if t.type == "table_open":
            rows = []
        elif t.type == "tr_open" and rows is not None:
            row = []
        elif t.type in ("th_open", "td_open") and row is not None:
            row.append("")
        elif t.type == "inline" and row is not None and rows is not None:
            row[-1] = t.content.strip()
        elif t.type == "tr_close" and rows is not None:
            rows.append(row)
            row = None
        elif t.type == "table_close":
            tables.append(rows)
            rows = None
    return tables


def review_findings(path):
    """{id: {"severity", "title"}} from a review's findings table -- the shape
    l3io-arch-review's references/review-report.md prescribes, IDs in the `#` column."""
    try:
        text = read_text(path)
    except OSError as e:
        raise SAError(2, f"cannot read review {path}: {e.strerror or e}")
    out = {}
    for rows in md_tables(text):
        if not rows:
            continue
        head = [c.strip().casefold() for c in rows[0]]
        if "#" not in head or "severity" not in head:
            continue
        ci, si = head.index("#"), head.index("severity")
        ti = head.index("finding") if "finding" in head else None
        for r in rows[1:]:
            fid = r[ci].strip().strip("`") if ci < len(r) else ""
            if not FINDING_ID_RE.match(fid):
                continue
            if fid in out:
                raise SAError(2, f"{path}: finding {fid} appears twice")
            title = r[ti] if ti is not None and ti < len(r) and r[ti] else fid
            out[fid] = {"severity": r[si].strip().strip("*").upper(), "title": title}
    return out


def load_dispositions(dpath, review_rel=None):
    from ruamel.yaml.comments import CommentedMap
    data = load_yaml(dpath)
    if data is None:
        data = CommentedMap()
        data["review"] = review_rel
        data["findings"] = CommentedMap()
    if not isinstance(data.get("findings"), dict):
        raise SAError(2, f"{dpath}: 'findings' is not a mapping")
    return data


def cmd_disposition(ctx, a):
    from ruamel.yaml.comments import CommentedMap
    review = ctx.abs(a.review)
    f = review_findings(review).get(a.finding)
    if f is None:
        raise SAError(2, f"{a.finding} is not in the findings table of {ctx.rel(review)}")
    if a.spec_alignment.lower() != "true" and a.disposition in SPEC_DISPOSITIONS:
        raise SAError(2, f"spec_alignment is off: {a.finding} can only be resolved-in-code "
                         f"or adr-justified")
    spec = adr = None
    if a.adr:
        if not os.path.isfile(ctx.abs(a.adr)):
            raise SAError(2, f"--adr {a.adr} does not exist")
        adr = ctx.rel(ctx.abs(a.adr))
    elif a.disposition == "adr-justified":
        raise SAError(2, "adr-justified needs --adr naming the accepted ADR")
    if a.disposition in SPEC_DISPOSITIONS:
        if not a.spec:
            raise SAError(2, f"{a.disposition} needs --spec <path>#<anchor>")
        hit, why = resolve_pointer(load_catalog(ctx), a.spec)
        if hit is None:
            raise SAError(2, f"--spec {a.spec}: {why}")
        if a.disposition == "spec-updated" and hit[3] != "architecture":
            raise SAError(2, f"spec-updated edits architecture sections only; {hit[0]} is a "
                             f"{hit[3]} spec -- record spec-proposal instead (ADR-0004)")
        spec = f"{hit[0]}#{hit[1]}"
    dpath = os.path.join(os.path.dirname(review), DISP_FILE)
    data = load_dispositions(dpath, ctx.rel(review))
    prior = data["findings"].get(a.finding)
    if prior is not None and (prior.get("commit") or prior.get("issue")):
        raise SAError(2, f"{a.finding} was already applied "
                         f"({prior.get('commit') or prior.get('issue')}); its disposition "
                         f"cannot change")
    e = CommentedMap()
    e["severity"], e["title"], e["disposition"] = f["severity"], f["title"], a.disposition
    e["spec"], e["adr"], e["commit"], e["issue"] = spec, adr, None, None
    data["findings"][a.finding] = e
    dump_yaml(dpath, data)
    print(f"OK disposition {a.finding} ({f['severity']}) -> {a.disposition}")
    return 0


def cmd_check_dispositions(ctx, a):
    m = EXPECT_RE.search(a.expect)
    if not m:
        raise SAError(2, f"--expect {a.expect!r} has no 'Blocker: N, Major: N, Minor: N'")
    review = ctx.abs(a.review)
    findings = review_findings(review)
    expected = dict(zip(SEVERITIES, map(int, m.groups())))
    got = {s: sum(1 for f in findings.values() if f["severity"] == s) for s in SEVERITIES}
    problems = []
    odd = sorted({f["severity"] for f in findings.values()} - set(SEVERITIES))
    if odd:
        problems.append(f"unknown severities in the findings table: {', '.join(odd)}")
    if got != expected:
        problems.append(f"parsed Blocker: {got['BLOCKER']}, Major: {got['MAJOR']}, Minor: "
                        f"{got['MINOR']} from {ctx.rel(review)} but the reviewer reported "
                        f"Blocker: {expected['BLOCKER']}, Major: {expected['MAJOR']}, Minor: "
                        f"{expected['MINOR']} -- is the findings table in the "
                        f"references/review-report.md shape, IDs in the # column?")
    data = load_dispositions(os.path.join(os.path.dirname(review), DISP_FILE))
    for fid, f in sorted(findings.items()):
        if f["severity"] in ("BLOCKER", "MAJOR") and fid not in data["findings"]:
            problems.append(f"{fid} ({f['severity']}) has no disposition")
    for p in problems:
        sys.stderr.write(f"check-dispositions: {p}\n")
    if problems:
        return 2
    print(f"OK check-dispositions: {len(findings)} finding(s), every BLOCKER/MAJOR disposed")
    return 0


# -- ADRs (one home: docs/adr/, ADR-0005) ------------------------------------------------------- #

DOC_ADR_RE = re.compile(r"^(\d{4})-.+\.md$")
LEGACY_ADR_RE = re.compile(r"^adr-(\d{4})-(.+)\.md$")
ADR_META_RE = re.compile(r"^-\s+\*\*(Status|Epic|Departs from spec):\*\*\s*(.*?)\s*$")


def epic_key(value):
    """'E003', 'e3', '003', '3' -> 'E003'; anything else (n/a, empty) -> None."""
    m = re.fullmatch(r"\s*E?(\d{1,3})\s*", str(value or ""), re.I)
    return f"E{int(m.group(1)):03d}" if m else None


def adr_meta(path):
    """The metadata bullets before the first `##` heading (assets/adr-template.md shape)."""
    meta = {}
    for line in read_text(path).splitlines():
        if line.startswith("## "):
            break
        m = ADR_META_RE.match(line)
        if m:
            meta[m.group(1)] = m.group(2).strip().strip("`")
    return meta


def all_adrs(ctx):
    out = []
    docs = os.path.join(ctx.project, "docs", "adr")
    if os.path.isdir(docs):
        for name in sorted(os.listdir(docs)):
            m = DOC_ADR_RE.match(name)
            if m:
                p = os.path.join(docs, name)
                meta = adr_meta(p)
                out.append({"path": ctx.rel(p), "number": int(m.group(1)), "home": "docs",
                            "epic": epic_key(meta.get("Epic")), "status": meta.get("Status", ""),
                            "departs": meta.get("Departs from spec", "")})
    if ctx.impl:
        for p in sorted(glob.glob(os.path.join(ctx.impl, "epic-*", "arch", "adr-*.md"))):
            m = LEGACY_ADR_RE.match(os.path.basename(p))
            em = re.search(r"epic-(\d{3})", os.path.basename(os.path.dirname(os.path.dirname(p))))
            if m and em:
                meta = adr_meta(p)
                out.append({"path": ctx.rel(p), "number": int(m.group(1)), "home": "legacy",
                            "epic": f"E{em.group(1)}", "status": meta.get("Status", ""),
                            "departs": meta.get("Departs from spec", "")})
    return out


def link_gaps(ctx, cat, adrs):
    """Accepted ADRs whose `Departs from spec:` section does not link back to them."""
    gaps = []
    for x in adrs:
        dep = (x["departs"] or "").strip()
        if not x["status"].lower().startswith("accepted") or not dep or dep.lower() == "n/a":
            continue
        if not PTR_RE.match(dep):
            gaps.append((x, dep, "not a pointer"))
            continue
        hit, _ = resolve_pointer(cat, dep)
        if hit is None:
            gaps.append((x, dep, "pointer does not resolve"))
            continue
        sec = hit[2]
        body = read_text(ctx.abs(hit[0])).splitlines()[sec.start - 1:sec.end]
        if not any(os.path.basename(x["path"]) in line for line in body):
            gaps.append((x, dep, "section does not link the ADR"))
    return gaps


def cmd_adrs(ctx, a):
    ek = epic_key(a.epic)
    if ek is None:
        raise SAError(2, f"--epic {a.epic!r} is not an epic key")
    rows = [x for x in all_adrs(ctx) if x["epic"] == ek]
    for x in rows:
        if x["home"] == "legacy":
            sys.stderr.write(f"WARN {x['path']} is in the old ADR home -- run "
                             f"/l3io-util-doctor migrate-adrs\n")
    if a.format == "json":
        print(json.dumps(rows, indent=2))
    else:
        for x in rows:
            print(x["path"])
    return 0


def cmd_check_links(ctx, a):
    adrs = all_adrs(ctx)
    if a.epic:
        ek = epic_key(a.epic)
        if ek is None:
            raise SAError(2, f"--epic {a.epic!r} is not an epic key")
        adrs = [x for x in adrs if x["epic"] == ek]
    gaps = link_gaps(ctx, load_catalog(ctx), adrs)
    for x, dep, why in gaps:
        print(f"{x['path']}: departs from {dep} -- {why}")
    if gaps:
        return 1
    print(f"OK check-links: {len(adrs)} ADR(s)")
    return 0


# -- CLI -------------------------------------------------------------------------------------- #

def build_parser():
    p = argparse.ArgumentParser(prog="spec-align.py",
                                description="Spec/implementation alignment for l3io-pm.")
    p.add_argument("--project-root", required=True)
    p.add_argument("--planning-root", default="")
    p.add_argument("--impl-root", default="")
    p.add_argument("--state-root", default="", help="default: <impl-root>/state")
    p.add_argument("--pm-status", default="", help="path to pm-status.py")
    p.add_argument("--spec-paths", default=None,
                   help="JSON list of project-relative paths/globs; replaces discovery")
    sub = p.add_subparsers(dest="cmd", required=True)

    b = sub.add_parser("build", help="build the spec index (no LLM)")
    g = b.add_mutually_exclusive_group()
    g.add_argument("--if-stale", action="store_true", help="rewrite only when the specs changed")
    g.add_argument("--check", action="store_true", help="exit 1 when stale; write nothing")
    b.set_defaults(func=cmd_build)

    cp = sub.add_parser("check-pointers", help="provenance: every dimension's Spec: line")
    g = cp.add_mutually_exclusive_group(required=True)
    g.add_argument("--story", nargs="+", help="gate mode: exit 2 on any problem")
    g.add_argument("--all", action="store_true",
                   help="report mode over every story: exit 1 on broken pointers")
    cp.set_defaults(func=cmd_check_pointers)

    se = sub.add_parser("sections", help="the stories' pointers as de-duplicated line ranges")
    se.add_argument("--stories", nargs="+", required=True)
    se.set_defaults(func=cmd_sections)

    dp = sub.add_parser("disposition", help="record one drift finding's disposition")
    dp.add_argument("--review", required=True)
    dp.add_argument("--finding", required=True, help="AD-{n} or SD-{nn}-{n}")
    dp.add_argument("--disposition", required=True, choices=list(DISPOSITIONS))
    dp.add_argument("--spec", default="", help="<path>#<anchor> (spec dispositions)")
    dp.add_argument("--adr", default="", help="the ADR (adr-justified; optional otherwise)")
    dp.add_argument("--spec-alignment", default="true", help="pm-execute's spec_alignment")
    dp.set_defaults(func=cmd_disposition)

    cd = sub.add_parser("check-dispositions", help="gate: every BLOCKER/MAJOR disposed")
    cd.add_argument("--review", required=True)
    cd.add_argument("--expect", required=True,
                    help="the reviewer's final 'Blocker: N, Major: N, Minor: N'")
    cd.set_defaults(func=cmd_check_dispositions)

    ad = sub.add_parser("adrs", help="an epic's ADRs, from docs/adr and the old home")
    ad.add_argument("--epic", required=True)
    ad.add_argument("--format", choices=["text", "json"], default="text")
    ad.set_defaults(func=cmd_adrs)

    cl = sub.add_parser("check-links", help="report ADRs their spec section does not link")
    cl.add_argument("--epic", default="")
    cl.set_defaults(func=cmd_check_links)

    # Later tasks register their subcommands above this line.
    return p


def main(argv=None):
    a = build_parser().parse_args(argv)
    try:
        return a.func(Ctx(a), a)
    except SAError as e:
        sys.stderr.write(f"spec-align.py {a.cmd}: {e}\n")
        return e.code


if __name__ == "__main__":
    sys.exit(main())
