#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "markdown-it-py>=3",
#   "mdit-py-plugins>=0.4",
#   "ruamel.yaml>=0.18",
#   "unidiff>=0.7",
#   "tenacity>=8",
# ]
# ///
"""
spec-align.py -- keeps a project's specs and its implementation in step, for l3io-pm.

Subcommands: build, check-pointers, sections, disposition, check-dispositions, adrs,
check-links, lease, sync-plan, propose, commit, reject, check-stale, migrate-adrs.

It never calls a model. Each spec-alignment point in l3io-pm-execute runs one of these
first, and the result decides whether an agent is dispatched at all.

Global flags come before the subcommand: --project-root (required), --planning-root,
--impl-root, --state-root (default <impl-root>/state), --pm-status, --spec-paths JSON.

Exit codes: 0 ok; 1 a report-mode check found problems; 2 a gate refused, or bad input;
5 the spec-sync lease is held by another owner.

Design: docs/superpowers/specs/2026-09-11-spec-alignment-design.md in the package repo;
decisions: docs/adr/0004-agents-edit-architecture-specs.md, docs/adr/0005-one-adr-home.md.
"""
import argparse
import fnmatch
import glob
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile

INDEX_FORMAT = 1
INDEX_REL = os.path.join("spec", "spec-index.md")
INDEX_MAX_LEVEL = 3
SUMMARY_CHARS = 100
SIZE_WARN_BYTES = 16384
HEADER_TITLE = "# Spec index — generated by spec-align.py; do not edit"
DIGEST_RE = re.compile(r"^# inputs-sha256: ([0-9a-f]{64})\b")
SPEC_PATHS_RE = re.compile(r"^# spec-paths: (.*)$")

# Spec kinds in precedence order: a name matching several kinds takes the first. The
# architecture, ux and prd patterns are copied verbatim from
# l3io-util-doctor/steps/layout-cleanup.md heuristic 5 -- check-docs check 13 compares them.
KINDS = (
    ("architecture", ("*architecture*", "*arch-spec*", "*system-design*", "*tech-design*")),
    ("ux", ("*ux-spec*", "*ux-design*", "*wireframe*", "*mockup*", "*ui-spec*")),
    ("prd", ("*requirements*", "*prd*", "*brief*", "*spec*")),
    ("epics", ("*epics*",)),
)
KIND_ORDER = {k: i for i, (k, _) in enumerate(KINDS)}


class SAError(Exception):
    """A refusal: `code` is the exit status; the message goes to stderr."""

    def __init__(self, code, msg):
        super().__init__(msg)
        self.code = code


class Ctx:
    """The paths every subcommand resolves against, from the global flags."""

    def __init__(self, a):
        self.project = os.path.abspath(a.project_root)
        self.planning = os.path.abspath(a.planning_root) if a.planning_root else None
        self.impl = os.path.abspath(a.impl_root) if a.impl_root else None
        self.state_root = (os.path.abspath(a.state_root) if a.state_root
                           else (os.path.join(self.impl, "state") if self.impl else None))
        self.pm_status = a.pm_status or None
        self.spec_paths_arg = None
        if a.spec_paths is not None:
            try:
                value = json.loads(a.spec_paths)
            except ValueError as e:
                raise SAError(2, f"--spec-paths is not JSON: {e}")
            if not isinstance(value, list) or not all(isinstance(x, str) for x in value):
                raise SAError(2, "--spec-paths must be a JSON list of strings")
            self.spec_paths_arg = value

    def need(self, *what):
        flags = {"impl": ("--impl-root", self.impl), "state": ("--state-root", self.state_root),
                 "pm": ("--pm-status", self.pm_status)}
        missing = [flags[w][0] for w in what if not flags[w][1]]
        if missing:
            raise SAError(2, f"this subcommand needs {', '.join(missing)}")

    def rel(self, p):
        return os.path.relpath(os.path.abspath(p), self.project).replace(os.sep, "/")

    def abs(self, p):
        return p if os.path.isabs(p) else os.path.join(self.project, p)

    def index_path(self):
        self.need("impl")
        return os.path.join(self.impl, INDEX_REL)


def _under(path, root):
    path, root = os.path.abspath(path), os.path.abspath(root)
    return path == root or path.startswith(root + os.sep)


def read_text(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def atomic_write(path, text):
    """Write via a sibling temp file + os.replace, so a reader never sees half a file."""
    d = os.path.dirname(os.path.abspath(path))
    os.makedirs(d, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=d, prefix=".spec-align-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as fh:
            fh.write(text)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


# -- markdown ------------------------------------------------------------------------------ #

_MD = None


def md():
    """One parser for every read. Anchors are computed over every heading level, so duplicate
    suffixes (-1, -2) count the same headings GitHub does; the index lists H1-H3 only."""
    global _MD
    if _MD is None:
        from markdown_it import MarkdownIt
        from mdit_py_plugins.anchors import anchors_plugin
        _MD = MarkdownIt("commonmark").enable("table").use(anchors_plugin,
                                                           min_level=1, max_level=6)
    return _MD


class Section:
    __slots__ = ("level", "title", "anchor", "start", "end", "summary")

    def __init__(self, level, title, anchor, start, end, summary):
        self.level, self.title, self.anchor = level, title, anchor
        self.start, self.end, self.summary = start, end, summary


def first_sentence(text):
    s = " ".join(text.split())
    m = re.match(r"(.+?[.!?])(?:\s|$)", s)
    if m:
        s = m.group(1)
    return s if len(s) <= SUMMARY_CHARS else s[:SUMMARY_CHARS - 1].rstrip() + "…"


def parse_sections(text):
    """Every heading as a Section. A section runs from its heading line to the line before
    the next heading of the same or a higher level (1-based, inclusive)."""
    tokens = md().parse(text)
    nlines = len(text.splitlines())
    heads = [(i, int(t.tag[1:]), t.attrs.get("id"), t.map[0], tokens[i + 1].content.strip())
             for i, t in enumerate(tokens) if t.type == "heading_open"]
    out = []
    for n, (i, level, anchor, line0, title) in enumerate(heads):
        end = nlines
        for _, level2, _, line2, _ in heads[n + 1:]:
            if level2 <= level:
                end = line2
                break
        stop = heads[n + 1][0] if n + 1 < len(heads) else len(tokens)
        summary = ""
        for j in range(i + 3, stop):
            if (tokens[j].type == "paragraph_open" and j + 1 < stop
                    and tokens[j + 1].type == "inline"):
                summary = first_sentence(tokens[j + 1].content)
                break
        out.append(Section(level, title, anchor, line0 + 1, max(end, line0 + 1), summary))
    return out


# -- discovery and the catalog -------------------------------------------------------------- #

def kind_of(name):
    low = name.lower()
    for kind, patterns in KINDS:
        if any(fnmatch.fnmatchcase(low, p) for p in patterns):
            return kind
    return None


def _kind_for_path(p):
    """A file takes its own name's kind, else its directory's (a sharded doc's section)."""
    return kind_of(os.path.basename(p)) or kind_of(os.path.basename(os.path.dirname(p)))


def recorded_spec_paths(ctx):
    """The spec-paths list the current index was built with, or None."""
    if not ctx.impl:
        return None
    p = os.path.join(ctx.impl, INDEX_REL)
    if not os.path.isfile(p):
        return None
    with open(p, encoding="utf-8") as fh:
        for n, line in enumerate(fh):
            if n > 4:
                break
            m = SPEC_PATHS_RE.match(line.rstrip("\n"))
            if m:
                try:
                    value = json.loads(m.group(1))
                except ValueError:
                    return None
                return value if isinstance(value, list) else None
    return None


def effective_spec_paths(ctx):
    """--spec-paths when given; else the list the index records (so doctor, which cannot read
    pm-execute's customize.toml, checks the same spec set); else [] (discover)."""
    if ctx.spec_paths_arg is not None:
        return list(ctx.spec_paths_arg)
    rec = recorded_spec_paths(ctx)
    return rec if rec is not None else []


def discover(ctx):
    """[(project-relative path, kind)], sorted. spec_paths replaces discovery entirely."""
    found = {}
    skip = os.path.join(ctx.impl, "spec") if ctx.impl else None      # never index the index
    patterns = effective_spec_paths(ctx)
    if patterns:
        for pat in patterns:
            for hit in glob.glob(os.path.join(ctx.project, pat), recursive=True):
                if os.path.isfile(hit) and hit.endswith(".md") and not (skip and _under(hit, skip)):
                    found[ctx.rel(hit)] = _kind_for_path(hit) or "other"
    elif ctx.planning and os.path.isdir(ctx.planning):
        for dirpath, dirnames, filenames in os.walk(ctx.planning):
            if skip and _under(dirpath, skip):
                dirnames[:] = []
                continue
            keep = []
            for d in sorted(dirnames):
                full = os.path.join(dirpath, d)
                kind = kind_of(d)
                if skip and _under(full, skip):
                    continue
                if kind and os.path.isfile(os.path.join(full, "index.md")):
                    for sub_dir, _, sub_files in os.walk(full):
                        for f in sub_files:
                            if f.endswith(".md"):
                                found[ctx.rel(os.path.join(sub_dir, f))] = kind
                else:
                    keep.append(d)
            dirnames[:] = keep
            for f in filenames:
                if f.endswith(".md"):
                    kind = kind_of(f)
                    if kind:
                        found[ctx.rel(os.path.join(dirpath, f))] = kind
    return sorted(found.items())


def load_catalog(ctx):
    """{rel: {"kind", "sections", "anchors", "error", "sha"}} for every discovered spec."""
    cat = {}
    for rel, kind in discover(ctx):
        e = {"kind": kind, "sections": [], "anchors": {}, "error": None, "sha": ""}
        try:
            with open(ctx.abs(rel), "rb") as fh:
                raw = fh.read()
        except OSError as exc:
            e["error"], e["sha"] = f"unreadable: {exc.strerror or exc}", "unreadable"
        else:
            e["sha"] = hashlib.sha256(raw).hexdigest()
            try:
                text = raw.decode("utf-8")
            except UnicodeDecodeError:
                e["error"] = "not UTF-8"
            else:
                e["sections"] = parse_sections(text)
                e["anchors"] = {s.anchor: s for s in e["sections"]}
        cat[rel] = e
    return cat


def inputs_hash(ctx, cat):
    h = hashlib.sha256()
    h.update(f"format={INDEX_FORMAT}\n"
             f"spec-paths={json.dumps(effective_spec_paths(ctx))}\n".encode())
    for rel in sorted(cat):
        h.update(f"{rel}\0{cat[rel]['sha']}\n".encode())
    return h.hexdigest()


def render_index(ctx, cat, digest):
    body, skipped, n_specs, n_sections = [], [], 0, 0
    for rel in sorted(cat, key=lambda r: (KIND_ORDER.get(cat[r]["kind"], 99), r)):
        e = cat[rel]
        if e["error"]:
            skipped.append(f"- skipped: {rel} ({e['error']})")
            continue
        n_specs += 1
        body.append(f"## {e['kind']} · {rel}")
        for s in e["sections"]:
            if s.level > INDEX_MAX_LEVEL:
                continue
            n_sections += 1
            summary = f": {s.summary}" if s.summary else ""
            body.append(f"- {rel}#{s.anchor} — {s.title}{summary} (L{s.start}–{s.end})")
    if skipped:
        body += ["## skipped", *skipped]
    if not cat:
        body.append("no spec docs found")
    text = "\n".join(body) + "\n"
    nbytes = len(text.encode("utf-8"))            # R12: the body below the header
    header = (f"{HEADER_TITLE}\n"
              f"# inputs-sha256: {digest}  ·  bytes: {nbytes:,}  ·  specs: {n_specs}  ·  "
              f"sections: {n_sections}\n"
              f"# spec-paths: {json.dumps(effective_spec_paths(ctx))}\n")
    return header + text, nbytes, n_specs, n_sections


def index_digest(path):
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as fh:
        for n, line in enumerate(fh):
            if n > 4:
                break
            m = DIGEST_RE.match(line)
            if m:
                return m.group(1)
    return None


def cmd_build(ctx, a):
    path = ctx.index_path()
    cat = load_catalog(ctx)
    digest = inputs_hash(ctx, cat)
    fresh = index_digest(path) == digest
    if a.check:
        if fresh:
            print(f"OK build --check: {ctx.rel(path)} is fresh")
            return 0
        print(f"STALE {ctx.rel(path)}: the specs changed since it was built "
              f"(or it does not exist) -- run build")
        return 1
    if a.if_stale and fresh:
        print(f"OK build: {ctx.rel(path)} is fresh; not rewritten")
        return 0
    text, nbytes, n_specs, n_sections = render_index(ctx, cat, digest)
    atomic_write(path, text)
    if nbytes > SIZE_WARN_BYTES:
        sys.stderr.write(f"WARN spec index is {nbytes:,} bytes (> {SIZE_WARN_BYTES:,}); every "
                         f"reviewer reads it -- consider trimming (spec §8)\n")
    print(f"OK build: wrote {ctx.rel(path)} ({n_specs} spec(s), {n_sections} section(s), "
          f"{nbytes:,} bytes)")
    return 0


# -- CLI -------------------------------------------------------------------------------------- #

def build_parser():
    p = argparse.ArgumentParser(prog="spec-align.py",
                                description="Spec/implementation alignment for l3io-pm.")
    p.add_argument("--project-root", required=True)
    p.add_argument("--planning-root", default="")
    p.add_argument("--impl-root", default="")
    p.add_argument("--state-root", default="", help="default: <impl-root>/state")
    p.add_argument("--pm-status", default="", help="path to pm-status.py")
    p.add_argument("--spec-paths", default=None,
                   help="JSON list of project-relative paths/globs; replaces discovery")
    sub = p.add_subparsers(dest="cmd", required=True)

    b = sub.add_parser("build", help="build the spec index (no LLM)")
    g = b.add_mutually_exclusive_group()
    g.add_argument("--if-stale", action="store_true", help="rewrite only when the specs changed")
    g.add_argument("--check", action="store_true", help="exit 1 when stale; write nothing")
    b.set_defaults(func=cmd_build)

    # Later tasks register their subcommands above this line.
    return p


def main(argv=None):
    a = build_parser().parse_args(argv)
    try:
        return a.func(Ctx(a), a)
    except SAError as e:
        sys.stderr.write(f"spec-align.py {a.cmd}: {e}\n")
        return e.code


if __name__ == "__main__":
    sys.exit(main())
